"use client";

import { useState } from "react";
import { motion, AnimatePresence } from "framer-motion";
import { 
  Bot, 
  Sparkles, 
  UserCheck, 
  FileCode, 
  AlertCircle, 
  CheckCircle2, 
  ArrowRight,
  Code
} from "lucide-react";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";

export function CretContextRoleAnimator() {
  const [promptType, setPromptType] = useState<"vague" | "cret">("cret");

  return (
    <div className="border border-zinc-200 dark:border-zinc-800 rounded-2xl p-5 md:p-6 bg-gradient-to-b from-zinc-50 to-white dark:from-zinc-900/90 dark:to-zinc-950 shadow-sm space-y-6">
      {/* Header */}
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-3 pb-4 border-b border-zinc-200 dark:border-zinc-800">
        <div>
          <div className="flex items-center gap-2">
            <Badge className="bg-purple-500/10 text-purple-600 dark:text-purple-400 border-purple-500/30 text-xs font-semibold">
              Pilar 4.1: C-R-E-T Framework
            </Badge>
            <span className="text-xs text-zinc-500 dark:text-zinc-400 font-mono">Context & Role Direction</span>
          </div>
          <h4 className="text-base font-bold text-zinc-900 dark:text-zinc-100 mt-1">
            Simulasi Pengaruh C (Context) & R (Role) Terhadap Kualitas Output AI
          </h4>
        </div>

        {/* Toggle Switch */}
        <div className="flex items-center gap-1 bg-zinc-200/70 dark:bg-zinc-800/80 p-1 rounded-xl shrink-0">
          <button
            type="button"
            onClick={() => setPromptType("cret")}
            className={`px-3 py-1.5 rounded-lg text-xs font-bold transition-all flex items-center gap-1.5 ${
              promptType === "cret"
                ? "bg-purple-600 text-white shadow-sm"
                : "text-zinc-600 dark:text-zinc-400 hover:text-zinc-900 dark:hover:text-white"
            }`}
          >
            <Sparkles className="w-3.5 h-3.5" />
            Dengan Context & Role (C-R)
          </button>
          <button
            type="button"
            onClick={() => setPromptType("vague")}
            className={`px-3 py-1.5 rounded-lg text-xs font-bold transition-all flex items-center gap-1.5 ${
              promptType === "vague"
                ? "bg-zinc-700 text-white shadow-sm"
                : "text-zinc-600 dark:text-zinc-400 hover:text-zinc-900 dark:hover:text-white"
            }`}
          >
            <Bot className="w-3.5 h-3.5" />
            Prompt Asal-Asalan (Vague)
          </button>
        </div>
      </div>

      {/* Comparison Grid */}
      <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
        {/* Left: Prompt Input Sent to LLM */}
        <div className="p-4 rounded-xl border border-zinc-200 dark:border-zinc-800 bg-white dark:bg-zinc-900/60 space-y-3">
          <div className="flex items-center justify-between text-xs font-bold text-zinc-700 dark:text-zinc-300">
            <span>Teks Instruksi Pengembang (Prompt):</span>
            <span className="font-mono text-zinc-400">
              {promptType === "cret" ? "C-R-E-T Pattern" : "Tanpa Metodologi"}
            </span>
          </div>

          <div className="p-3.5 rounded-lg bg-zinc-50 dark:bg-zinc-800/50 border border-zinc-200 dark:border-zinc-700 text-xs font-mono leading-relaxed space-y-2">
            {promptType === "cret" ? (
              <>
                <div className="text-purple-600 dark:text-purple-400 font-bold">
                  [ROLE]: &quot;Bertindaklah sebagai Senior Cloud Architect &amp; Next.js 16 Specialist.&quot;
                </div>
                <div className="text-blue-600 dark:text-blue-400">
                  [CONTEXT]: &quot;Saya sedang membangun aplikasi web serverless tugas perkuliahan dengan database Supabase PostgreSQL.&quot;
                </div>
                <div className="text-zinc-700 dark:text-zinc-300">
                  &quot;Buatkan struktur fungsi server action untuk menyimpan data tugas baru.&quot;
                </div>
              </>
            ) : (
              <div className="text-zinc-600 dark:text-zinc-300 py-4">
                &quot;Tolong buatkan fungsi simpan data tugas.&quot;
              </div>
            )}
          </div>

          <div className="text-[11px] text-zinc-500 leading-relaxed">
            {promptType === "cret"
              ? "✅ AI memahami standar ekspektasi (Level Senior) dan arsitektur target (Serverless Next.js 16)."
              : "⚠️ Tanpa batasan persona dan arsitektur, AI menebak secara acak berdasarkan jutaan kode usang di internet."}
          </div>
        </div>

        {/* Right: Code Generated by LLM */}
        <div className="p-4 rounded-xl border border-zinc-200 dark:border-zinc-800 bg-[#1e1e1e] text-zinc-200 font-mono text-xs space-y-2 flex flex-col justify-between">
          <div className="space-y-2">
            <div className="flex items-center justify-between text-zinc-400 pb-1 border-b border-zinc-800 text-[11px]">
              <span>Respons Kode yang Dihasilkan AI:</span>
              <span className={promptType === "cret" ? "text-emerald-400" : "text-amber-400"}>
                {promptType === "cret" ? "Modern & Aman" : "Usang / Tidak Standar"}
              </span>
            </div>

            <pre className="text-xs leading-relaxed overflow-x-auto text-zinc-300 p-1">
              <code>
                {promptType === "cret" ? `// src/actions/tasks.ts ('use server')
"use server";

import { supabase } from "@/lib/supabase";
import { revalidatePath } from "next/cache";

export async function createTask(formData: FormData) {
  const title = formData.get("title") as string;
  await supabase.from("tasks").insert({ title });
  revalidatePath("/dashboard");
}` : `// Kode hasil tebakan asal-asalan:
const express = require('express');
const router = express.Router();
const mysql = require('mysql');

router.post('/api/tasks', (req, res) => {
  // ⚠️ Menggunakan Express & MySQL usang, bukan Next.js 16!
  const sql = "INSERT INTO tasks VALUES (...)";
  db.query(sql, (err, result) => res.json(result));
});`}
              </code>
            </pre>
          </div>

          <div className={`p-2.5 rounded-lg text-[11px] font-sans ${
            promptType === "cret"
              ? "bg-emerald-950/60 text-emerald-300 border border-emerald-500/30"
              : "bg-amber-950/60 text-amber-200 border border-amber-500/30"
          }`}>
            {promptType === "cret" ? (
              <span className="flex items-center gap-1.5">
                <CheckCircle2 className="w-4 h-4 text-emerald-400 shrink-0" />
                <span>Langsung kompatibel dengan Next.js 16 App Router dan standar Server Actions.</span>
              </span>
            ) : (
              <span className="flex items-center gap-1.5">
                <AlertCircle className="w-4 h-4 text-amber-400 shrink-0" />
                <span>Gagal total. Menggunakan Express dan MySQL yang tidak relevan dengan stack kuliah.</span>
              </span>
            )}
          </div>
        </div>
      </div>
    </div>
  );
}
